# -*- coding: utf-8 -*-
"""Bookkeepings

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f3obHfqayBGm5zwxIJ16chDXr-kToDkq
"""

def make_transaction (acc, price, quantity, buy):
  
  quant=-1
  balance=-1
  for key,value in acc.items():
    quant=value
    balance=key
  fprice= quantity * price
  if buy==True: #if you are buying
    if (balance>= fprice):
      balance=balance-fprice
      quant= quant+quantity
    else : #if you have lesser balance than the money required
      t=balance//price
      balance=balance-(t*price)
      quant=quant+t
  else:  #if you are selling
    if (quant>=quantity): 
      balance=balance+fprice
      quant=quant-quantity
    else:
      sell2=quant*price
      balance=balance+ sell2
      quant=0

  acc.clear()
  acc[balance]=quant

  print ('Your current balance is ', balance)
  print('\n')
  print ('The number of stocks you own is ', quant)

print ('Enter your current balance')
balance=float(input())
print ('\n Enter the number of stocks you own')
quantity=int(input())

while (True):
  print ('Do you want to make a transaction? Press 1 for yes and 0 for no')
  choice=int(input())
  if (choice==1):
    print('\n Enter price')
    price=float(input())
    print(' \n Enter quantity')
    quantity=int(input())
    print ('\n Buy or sell? Enter True for yes and False for no ')
    buy=bool (input())
    acc={}
    acc[balance]=quantity
    make_transaction (acc, price, quantity, buy)
  else:
    print ('Thank you')
    break

