# -*- coding: utf-8 -*-
"""Question_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ARrgfClxTuzz2hZnLF8wtLzkdaNbcXe6
"""

import pandas as pd
import numpy as np

def read_data (data1):
  df=pd.DataFrame (data=data1)
  return df

def data_statistics (df):
  count_stat= df.count()
  print ('\n')
  print ('Count Stats')
  print (count_stat)
  mean_stat = df.mean (axis=0, skipna=True)
  print ('\n')
  print('Mean Stats')
  print (mean_stat)
  std_stat= df.std (axis=0, skipna=True)
  print ('\n')
  print ('Standard Deviation')
  print (std_stat)
  max_stat= df.max()
  print ('\n')
  print ('Maximum')
  print (max_stat)
  min_stat=df.min()
  print ('\n')
  print ('Minimum')
  print (min_stat)
  median_stat=df.median(axis=0)
  print ('\n')
  print ('Median')
  print (median_stat)
  Q1_stat=df.quantile ([0.25], axis=0)
  print ('\n')
  print ('Q1')
  print (Q1_stat)
  Q3_stat = df.quantile ([0.75], axis=0)
  print ('\n')
  print ('Q3')
  print (Q3_stat)

!wget --no-check-certificate \
https://raw.githubusercontent.com/shivam2199/DAta_sets/master/NFLX.csv

d1=pd.read_csv ('NFLX.csv')
df=read_data(d1)

df

data_statistics (df)

